[package]
name = "habitat_net"
version = "0.8.0"
authors = ["Adam Jacob <adam@chef.io>", "Jamie Winsor <reset@chef.io>", "Fletcher Nichol <fnichol@chef.io>", "Joshua Timberman <joshua@chef.io>", "Dave Parfitt <dparfitt@chef.io>"]
workspace = "../../"

[dependencies]
fnv = "*"
hyper = "*"
iron = "*"
lazy_static = "*"
libc = "*"
log = "*"
num_cpus = "*"
persistent = "*"
protobuf = "*"
rustc-serialize = "*"
time = "*"
unicase = "*"

[dependencies.zmq]
# git = "https://github.com/erickt/rust-zmq.git"
git = "https://github.com/reset/rust-zmq.git"
branch = "habitat"

[dependencies.habitat_builder_protocol]
path = "../builder-protocol"

[features]
functional = []
