pkg_name=bar
pkg_origin=core
pkg_version=0.1.0
pkg_description=""
pkg_upstream_url=
pkg_license=('Apache-2.0')
pkg_maintainer="The Habitat Maintainers <humans@habitat.sh>"
pkg_source=http://example.com/${pkg_name}-${pkg_version}.tar.gz
pkg_shasum=
pkg_bin_dirs=(bin)
pkg_build_deps=(core/make core/gcc)
pkg_deps=(core/glibc)
